---
# tasks file for common
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install common packages
  package: 
    name: '{{ common_pkgs }}'
    state: present

- name: Ensure timezone is set
  file: path=/etc/localtime state=link src="/usr/share/zoneinfo/{{ common_timezone }}" force=true

- name: Ensure /root/tmp is available
  file: path=/root/tmp state=directory owner=root group=root mode=0700

